### ISSUE TITLE
'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by un-dead-21** [patrickhilker/tedee_hass_integration#10]
Cant get it working after update from previous version. Tried removing from HACS and reinstalling new version as fresh, absolutely no difference except for losing all my 4 entities of course :/. Any idea where's the problem please?

Also updated HA to latest, now on 
Home Assistant 2023.6.3
Supervisor 2023.06.2
Operating System 10.3

Logger: custom_components.tedee
Source: custom_components/tedee/__init__.py:37
Integration: Tedee ([documentation](https://github.com/patrickhilker/tedee_hass_integration), [issues](https://github.com/patrickhilker/tedee_hass_integration/issues))
First occurred: 6:10:48 PM (17 occurrences)
Last logged: 6:21:40 PM

'NoneType' object is not subscriptable

**Comment by zweckj** [comment]
Not sure where this might be coming from... Can you "load full logs" and check if you can find a full call stack there?

**Comment by un-dead-21** [comment]
Just for future reference if helpful to anyone:
There's no call stack in logs, it was just one liner error.

Several restart of HA didnt help, but what made things different was restarting the lock bridge (pull it out of socket and back). However after this the integration was stuck on "initializing". Could pull on some doors but not lock/unlock. Different errors in logs.

Ended up just wiping it out and re-installing the previous version which thanks god works seamlessly (as it did before). Will try again in couple months time, maybe things will improve/stabilize.

**Comment by zweckj** [comment]
If you could add the errors that would help a lot. Otherwise I have no way to improve the code, because I don't get any errors...

**Comment by LordShadowen** [comment]
I'm finding the exact same problem. 

Did a full update to latest of HA and HACS components. The Tedee integration was stuck on "initializing", even after a couple of restarts.
Tried removing it and adding it again, with brand new Personal Key. Got stuck again, never finished the process.

But in my case, I see no errors or warning at all in the log.  Is there something special I should enable to get more logging? My logger in configuration.yaml is on "default: warn"

Just like @un-dead-21, I reverted to the previous version in HACS and now it's working again. 

Is there anything else I can try?

**Comment by zweckj** [comment]
You could enable debug logging in the integration's settings and see if it gives you anything (it should at least log all your locks it can find). 
How many/what kind of locks do you have? Are you on the latest firmware?

**Comment by un-dead-21** [comment]
Zweckj: understood (im dev too so I know), but in the logs there really wasnt a single useful line up to a point where I was thinking maybe this is knock on effect from different malfunctioning HACS. 

Re-init/new integration would end up with "Unknown (or unexpected) error" with no reference in the logs. Also not very helpful. Never tried the debug logging though.

For reference: I am on latest FW, have 4 locks (tedee pro), 2 keypads + bridge obviously.

**Comment by LordShadowen** [comment]
I've enabled "Debug logging" and updated to latest.
This time I did get an error on the log (which is kind of strange, an error should have appeared regardless of the "debug" setting...)

Anyway, this is what I got:

2023-06-29 17:58:34.982 ERROR (MainThread) [homeassistant.bootstrap] Error setting up integration tedee - received exception
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/setup.py", line 102, in async_setup_component
    return await task
           ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/setup.py", line 326, in _async_setup_component
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/tedee/__init__.py", line 49, in async_setup_entry
    await hass.config_entries.async_forward_entry_setups(entry, PLATFORMS)
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1365, in async_forward_entry_setups
    await asyncio.gather(
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 1393, in async_forward_entry_setup
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 387, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/lock/__init__.py", line 129, in async_setup_entry
    return await component.async_setup_entry(entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity_component.py", line 187, in async_setup_entry
    return await self._platforms[key].async_setup_entry(config_entry)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    return await self._async_setup_platform(async_create_setup_task)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    await asyncio.gather(*pending)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 471, in async_add_entities
    await asyncio.gather(*tasks)
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 537, in _async_add_entity
    await entity.async_device_update(warning=False)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 784, in async_device_update
    await self.async_update()
  File "/config/custom_components/tedee/lock.py", line 81, in async_update
    self._available = await self._client.update(self._id)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytedee_async/TedeeClient.py", line 265, in update
    await self.get_state()
  File "/usr/local/lib/python3.11/site-packages/pytedee_async/TedeeClient.py", line 216, in get_state
    raise TedeeClientException(f"Error during getting state. Status code {response.status}")
pytedee_async.TedeeClientException.TedeeClientException: Error during getting state. Status code 429

**Comment by zweckj** [comment]
@LordShadowen thanks. Do you have more than 1 device as well? If yes, how many?

**Comment by LordShadowen** [comment]
Yes - 16 locks over 8 bridges

**Comment by zweckj** [comment]
Somehow seems to be related to rate limits then because it (so far) only affects you two with multiple locks and would explain why I have zero issues with my single lock... will look into it!

**Comment by zweckj** [comment]
@LordShadowen @un-dead-21 could you please test if pre-release [2026.6.1b1](https://github.com/patrickhilker/tedee_hass_integration/releases/tag/2022.2.0b1) fixes your issues

**Comment by LordShadowen** [comment]
I was going to test it and saw that there was a newer 2023.7.0. I've tried that, and it works 👍

**Comment by zweckj** [comment]
Perfect, thanks for the confirmation!
