### ISSUE TITLE
[Improvement Proposal] Lock only mode

### ISSUE THREAD

**Issue by bzumik1** [patrickhilker/tedee_hass_integration#11]
Hi just an idea, would it be possible to add lock only mode? Just to prevent unintended unlocks?

**Comment by zweckj** [comment]
Not possible, because it’s not how Home Assistant locks work. You can always create a button for only locking your the door in a template.

**Comment by bzumik1** [comment]
Thanks for response Zweckj, maybe Tedee could create token with only lock rights. This way the button to unlock would be there but HA would not be able to use it.

**Comment by zweckj** [comment]
Not just doing anything on clicking the "lock" button would of course be possible, but it's a quite hacky solution, which I don't like.

**Comment by bzumik1** [comment]
I agree

**Comment by patrickhilker** [comment]
Should be resolved with 2023.7.0
