### ISSUE TITLE
[Bug] Unlock opens the door

### ISSUE THREAD

**Issue by bzumik1** [patrickhilker/tedee_hass_integration#12]
Hi, there is bug that when **lock.unlock** is called the latch is pressed and door opens. This should only happen when **lock.open** is called, **lock.unlock** should only unlock the door but they should stay closed. This is very dangerous bug because you can open your door when you are on vacation and there will be no one to close them.

**Comment by patrickhilker** [comment]
Should be resolved with 2023.7.0
