### ISSUE TITLE
Connected attribute changed from "true" to "false" since 2023.06

### ISSUE THREAD

**Issue by tunip** [patrickhilker/tedee_hass_integration#16]
Hello, thx for you great tedee HA integration. Everything is working fine so far.

One small thing since version 2023.06 is, that the "Connected" attribute of the lock changed from "true" to "false".

![image](https://github.com/patrickhilker/tedee_hass_integration/assets/11404472/df841724-5909-431d-b984-f875978f717f)

I use this attribute in my automation as a condition (only lock the door if it is connected).

**Comment by bzumik1** [comment]
Same for me.

**Comment by patrickhilker** [comment]
Would you mind checking out [2023.7.1b1](https://github.com/patrickhilker/tedee_hass_integration/releases/tag/2023.7.1b1)
