### ISSUE TITLE
State 3 is not always "jammed"

### ISSUE THREAD

**Issue by LordShadowen** [patrickhilker/tedee_hass_integration#17]
In the 2023.7.0 version, locks with the numeric state 3 are represented as "jammed". However, I don't believe this is correct.

In the Tedee app these are reported as "semi-locked".

It happens on my locks quite frequently - some locks require a large rotation between locked and unlocked during calibration. When opened manually, if the person leaves it unlocked but very close to the lock position, the system is not quite sure of the state and reports as "semi-locked"

It is possible to actually be "jammed" (which is rare), and I don't know what numerical state that is, but it most likely has a different number.

**Comment by patrickhilker** [comment]
Would you mind checking out [2023.7.1b1](https://github.com/patrickhilker/tedee_hass_integration/releases/tag/2023.7.1b1)

**Comment by LordShadowen** [comment]
Fixed as well :)
It now just shows as unlocked. 

This is perfectly fine for my purposes, but would it make sense to have a "semi-locked" state to mimic the official Tedee app? What do you think?

**Comment by LordShadowen** [comment]
Yes, I've seen it. It has a blinking icon and everything :)

Also, here is the table of all possible states:
https://tedee-tedee-api-doc.readthedocs-hosted.com/en/latest/enums/lock-state.html

I don't see a "jammed" state, but apparently there is an event triggered when that happens:
https://tedee-tedee-api-doc.readthedocs-hosted.com/en/latest/enums/event-type.html?highlight=jammed#event-type

I've actually tried to jam mine one of mine on purpose to see what state it reports, but it's harder than it sounds. If I could do that, I could check what state number it reports...

**Comment by zweckj** [comment]
It is in whatever state it was when it jammed. Most likely 3, that's why I initially put 3 there.


> I am not really into it, but it seems as there is a jammed state 🤔
> 
> https://github.com/home-assistant/core/blob/dev/homeassistant/components/lock/__init__.py#L21C18-L21C18

Yes there is a jammed state Patrick and it should now be set correctly as of #20. What I was referring to doesn't exist in HA is a "semilocked state", hence the extra attribute in #21

**Comment by patrickhilker** [comment]
Ah, sorry, got that wrong. Thank you!

**Comment by LordShadowen** [comment]
So, does that mean you are able to get that "jammed" event on HA, regardless of number state?

**Comment by zweckj** [comment]
I believe except the active ones (locking, unlocking, pulling, etc.)
