### ISSUE TITLE
Cannot see tedee integration while trying to add from HA

### ISSUE THREAD

**Issue by cayco** [patrickhilker/tedee_hass_integration#2]
I cannot see this integration when I'm trying to do steps from the instruction: `Go to the integrations page (Configuration - Devices & Services). Click the "+ Add Integration" button in the lower left corner and look for the "tedee" integration`

Steps to reproduce:
- install tedee_hass_integration in HACS
- restart
- try to add integration

There is nothing in logs, except that HA reads the integration and gives the warning on non-standard integration.

https://github.com/joerg65/tedee_lock works perfectly.

HA version: 2022.3.3
tedee_hass_integration version: 2022.2.0

**Comment by patrickhilker** [comment]
> https://github.com/joerg65/tedee_lock works perfectly.

I assume this is the problem - please uninstall it before using this integrations and check if it works.

**Comment by patrickhilker** [comment]
@cayco Did that help solving your issue?
