### ISSUE TITLE
Upstream repository situation

### ISSUE THREAD

**Issue by zweckj** [patrickhilker/tedee_hass_integration#22]
Hey @patrickhilker,
what is the situation with the upstream repository? Because I think it is confusing to new users to have two HACS tedee integrations which both appear active for new users?

What's your plan moving forward?
- merge back to upstream?
- disconnect from upstream (and ask joerg to set to archive)?

**Comment by patrickhilker** [comment]
To be honest, I never thought about that. I assume it is not that much confusing, as only this integration is available at the default HACS repository.

I don't even know what happens to the HACS integration if we merged to upstream.

**Comment by zweckj** [comment]
I don't know what would happen either tbh. 
I just noticed that the upstream appears first on Google and a couple of issues have been opened there recently which actually concerned this fork...

**Comment by patrickhilker** [comment]
I assume looking at the integration and its users it would be the best to add @joerg65 as a maintainer here, so he can keep up his work (that is possible, isn't it? I am a GitLab guy 😄) and to archive his repo. @joerg65 what do you think?

**Comment by zweckj** [comment]
yes, you can add additional maintainers. I agree with that approach as we don't know what a merge will do. At least disconnecting from the upstream will make clear that this is its own integration now. @joerg65 can then decide on his own whether he will continue do work on his own version. Once you're ready you can just use [GitHub's Chatbot](https://support.github.com/contact?tags=rr-forks&subject=Detach%20Fork&flow=detach_fork)  to do the detaching.

**Comment by patrickhilker** [comment]
Doen - that was an extremely awesome experience 😄

**Comment by joerg65** [comment]
It's OK for me. We agreed already about. I have archived my repo now. Best wishes and come back to me whenever is needed!
