### ISSUE TITLE
IMPORTANT: Reduce frequency of API requests and use alternative Sync endpoint

### ISSUE THREAD

**Issue by konradsikorski** [patrickhilker/tedee_hass_integration#27]
Dear Home Assistant community,

I am reaching out to you on behalf of Tedee organization. We have been observing an influx of API requests from your integration with our Tedee smart lock. The current request frequency, which is set to every 15 seconds, is significantly high and impacting our system.

We kindly ask you to adjust the frequency of the API requests to a more sustainable rate. Could you please modify the interval to 1 hour instead of the current 15 seconds?

Additionally, to check the lock status more frequently, we recommend using our Sync endpoint (https://tedee-tedee-api-doc.readthedocs-hosted.com/en/latest/endpoints/lock/sync.html). It provides real-time updates and would efficiently balance the request load while providing timely lock status information.

We appreciate your attention to this matter. We value your cooperation in ensuring optimal performance and user experience for all parties involved.

Please let us know if you need more information or assistance in making this adjustment.

**Comment by konradsikorski** [comment]
#29 please accept this change

**Comment by patrickhilker** [comment]
Thank you for hitting us up. 👍🏻  Unfortunately, updating the lock status only once every hour makes this integration pretty useless. Are there so much more users, or are the requests more frequent? The 15 seconds interval is not new.

I think it should be possible to switch to the sync-endpoint in the [upstream lib](https://github.com/zweckj/pytedee_async). Is there a difference other than the amount of data that is returned?

**Comment by zweckj** [comment]
@konradsikorski thanks for hitting us up. 

- I don’t see the benefit of using the sync endpoint as I'm also only hitting the /my/lock endpoint once for all locks a user has, even worse I‘d need an additional request to get all the information 
- We can talk about 30 seconds, but 3600 seconds definitely is not viable 
- The latest version should have reduced total API hits quite significantly, as we were previously hitting the API multiple times to get different properties and I implemented the DataCoordinator specifically to update all locks with a single call (if no actions happen)
- I found a bug where an action will trigger an unnecessary API call (will fix it) but I'm not sure how much the actions contribute to the overall load
- what would **really** help is you providing a WebSocket endpoint, so we only need to hit the API once and can subscribe to any changes. Would benefit us as well. 

Looking forward to working with you guys,
Josef

**Comment by zweckj** [comment]
@konradsikorski ok, because the PR would have exactly done that: Get the data only once per hour. 
I still don't see the difference between htting /my/locks and /my/locks/sync but I will try to comply. What is the rate limit on the sync endpoint? 
I still would love a WebSocket endpoint though, so we can get the state changes immediately 😊

**Comment by zweckj** [comment]
@konradsikorski would the changes in PR #32 be fine for you? I'm proposing to query the /my/lock endpoint once every hours to get changes related to pull_spring etc. and am otherwise hitting /sync every 15 seconds. I can of course not guarantee that the user doesn't reload the integration, which would cause another hit to /my/lock

**Comment by LordShadowen** [comment]
> We also work on local API so your integration can work in a local network without internet access. We will share the preview version with all our integrators soon.

This would be **fantastic**  👍 👍 👍

**Comment by konradsikorski** [comment]
@zweckj looks good, thank you for this change

**Comment by zweckj** [comment]
thanks for confirming, released as [2023.7.4](https://github.com/patrickhilker/tedee_hass_integration/releases/tag/2023.7.4)
