### ISSUE TITLE
Integrate pull spring

### ISSUE THREAD

**Issue by Magix3D** [patrickhilker/tedee_hass_integration#3]
Hello,
don't know, if that request is correct here, but I'll just try.
Is it possible to integrate an option to add a seperate button to let one pull the spring if the door is already unlocked?
Regards

**Comment by nadimaraufar** [comment]
Ass,
Haii, hello..
Hari ini esok atau lusa, selama saya msh berada di dunia entah apa yg akan saya lakukan dan kerjakan semua bertujuan demi kehidupan yg akan membawa ke diri dan jiwa serta hidup yg baik menjadi lebih baik lg dan bertahan di titik sempurna menuju keistimewaan.
Apapun yg buat dan lakuakan semua membawa keberuntungan 10 banding 1000 dari apa yg saya keluarkan walau tidak dengan modal sekalipun, tanpa ada ending yg merugikan serta menyulitkan apapun itu memberikan keajaiban sampai waktu dimana saya berada di titik tsb, saya juga ingin dan pasti akan melakukan hal yg dapat membantu serta memberikan kebahagian yg bermanfaat bagi siapapun orang yg menjalani kehidupan di dunia dng semesta yg senang bercanda serta sedikit kejam ini,.
Apakah saya seberuntung itu.?
Semoga alam semesta mendengar serta meng AMIN kan Doa dan mngabulkan keinginan saya salah satu nya dari jutaan atau milyaran manusia di muka bumi ini..
`DREAMING.?? (PRAYING)

**Comment by bernysk** [comment]
I second this request, I did not enable auto pull spring and would appreciate separate button for the pull spring. The lock only unlocks and door does not open. Thank you!

**Comment by bastiaanterhorst** [comment]
@bernysk you can use lock.open to pull the spring.

**Comment by patrickhilker** [comment]
I actually never used that feature. Will give it a try and take a look into it if it does not work. I hope to get this done by the end of january.

**Comment by rsporsche** [comment]
I don't know if this is out of date but the lock.open works for me. So I guess this could be closed?

**Comment by patrickhilker** [comment]
Should be implemented with version 2023.6.0.
