### ISSUE TITLE
Locking issues after upgrading to 2023.7.4

### ISSUE THREAD

**Issue by vytautasgimbutas** [patrickhilker/tedee_hass_integration#33]
After recent upgrades I've noticed that the lock sometimes doesn't lock. This happens to me every day or at least every other day. My setup is to automatically lock the lock (from HomeAssistant) when the alarm is in arming state and the second the doors are closed. It goes through an intermediary status "Locking" but falls back to "Unlocked". There aren't any logs in the HomeAssistant log (maybe they aren't enabled tho). Since the status "Locking" is also visible in the app I assume it could be a fault of API rather than the hardware (Hub, Lock). 

Overall, the cloud version is more unstable (also status updates take longer) and a local control would be probably the best solution. Not sure if this can be solved with the current API but I've wanted to raise an issue, see if any other people have the same problem and ask @konradsikorski for support.

<img width="764" alt="Screenshot 2023-08-01 at 1 41 25 PM" src="https://github.com/patrickhilker/tedee_hass_integration/assets/1172971/86c502c0-803b-46a1-9171-c6a91eb6d99e">
<img width="1175" alt="Screenshot 2023-08-01 at 1 44 12 PM" src="https://github.com/patrickhilker/tedee_hass_integration/assets/1172971/4a0c4bc8-3705-4f30-8342-e00e9ea72c72">

**Comment by vytautasgimbutas** [comment]
@konradsikorski maybe you could share ETA on the local control support?

**Comment by zweckj** [comment]
You can enable debug logs and check if you find someting in there. Don't expect support from tedee here, this is not an official integration, for that email them instead.
