### ISSUE TITLE
Error fetching tedee API coordinator data

### ISSUE THREAD

**Issue by garaig** [patrickhilker/tedee_hass_integration#37]
Since August I frequently get error messages from the customer component when try to lock:

Error fetching tedee API coordinator data: ('Querying API failed. Error: %s', TimeoutError())
Error fetching tedee API coordinator data: ('Querying API failed. Error: %s', ClientConnectorError(ConnectionKey(host='api.tedee.com', port=443, is_ssl=True, ssl=None, proxy=None, proxy_auth=None

Is there a solution for this problem?

**Comment by zweckj** [comment]
I don't have those, but looks like your bridge can't reach tedee's API. Check your bridge's WiFi and your network settings in general.

**Comment by zweckj** [comment]
closing as stale, please re-open in case you need further assistance.
