### ISSUE TITLE
 icon color

### ISSUE THREAD

**Issue by Duese911** [patrickhilker/tedee_hass_integration#39]
why is the lock icon displayed in red when the door is unlocked? Wouldn't it be more logical if open was green? Am I doing something wrong?

**Comment by bzumik1** [comment]
In my eyes it is locked -> secure -> green, unlocked -> unsecure -> red. But I have to admit that it was confusing for me as well at beginning.

**Comment by Duese911** [comment]
OK, I find it a bit strange.
Red is closed, you can't get in, it's occupied or something like that.
For me, green means it is free and the door can be opened
