### ISSUE TITLE
Add information who opened/closed the lock

### ISSUE THREAD

**Issue by niwi-hh** [patrickhilker/tedee_hass_integration#4]
Could you please add the information who opened / closed the lock? I would like to use this information as a trigger point. This information is available on the activity log of the native app. I hope it can be accessed via the api too.

**Comment by patrickhilker** [comment]
Unfortunately this seems to be not possible, as the API cannot send an event to Home Assistant when anything happens. This plugin only pulls the state of the lock (opened/locked).

But it should be possible to trigger automations when someone calls the service in Home Assistant.
