### ISSUE TITLE
Remove Locks from Integration

### ISSUE THREAD

**Issue by bzumik1** [patrickhilker/tedee_hass_integration#48]
Hello,

I trust I haven't overlooked any details, but I seem to be unable to find an option to remove locks from this integration. The integration automatically loads all locks from my tedee account. As I have tedee locks in multiple locations, I would appreciate guidance on selecting only those that should be controlled by Home Assistant. Any help on this matter would be greatly appreciated. Also please notice that those locks are not even connected to bridge -> so they are showing incorrect/unuseful info.

<img width="1235" alt="image" src="https://github.com/patrickhilker/tedee_hass_integration/assets/32042186/8f63a116-a976-4437-b791-3c31484f507c">

**Comment by zweckj** [comment]
added a basic option to remove locks in 2024.1.0b1
