### ISSUE TITLE
Make This Official HA Integration

### ISSUE THREAD

**Issue by bzumik1** [patrickhilker/tedee_hass_integration#49]
Hello,

I'm curious if there are any plans to integrate this into the core of Home Assistant and make it an official Home Assistant integration. I find this integration to be excellent, and it would be fantastic to see it included in the official list. I'm aware that there's ongoing work on the implementation of a local API, which seems like a significant enhancement. Could you shed some light on any challenges or reasons that might be hindering its transition to an official integration in Home Assistant?

Thank you for your time and effort.

**Comment by zweckj** [comment]
Yes, it's planned. In fact I already opened the PR on the official core repo, but am missing the required reviews from maintainers https://github.com/home-assistant/core/pull/102846.

**Comment by bzumik1** [comment]
Sounds perfect, thanks for the update!

**Comment by zweckj** [comment]
Will be part of HA 2024.2.

**Comment by bzumik1** [comment]
Sounds great! Awesome work, looking forward to it.
