### ISSUE TITLE
jammed instead of 'semi locked' with local API

### ISSUE THREAD

**Issue by niwi-hh** [patrickhilker/tedee_hass_integration#50]
I am using the dev version with the local integration only. After using the lock by the integration it often show the status "jammed" although it isn't by view or by the official app. The app show as status "semi locked" instead. This is also the status according to the attributes of the lock in Home Assistant. Maybe the status "semi locked" is just misinterpreted by the integration.

Here are some data:
- Tedee Pro lock with firmware 2.216579 (latest)
- latest dev-version of the integration
- I am only using the local part of the integration, but separately I use the app too
- "Unlock also pulls latch" is turned off

Here is the shortened content of the diagnostic file (without stuff from other custom integrations):```

{
  "home_assistant": {
    "installation_type": "Home Assistant OS",
    "version": "2023.12.1",
    "dev": false,
    "hassio": true,
    "virtualenv": false,
    "python_version": "3.11.6",
    "docker": true,
    "arch": "x86_64",
    "timezone": "Europe/Berlin",
    "os_name": "Linux",
    "os_version": "6.1.63-haos",
    "supervisor": "2023.11.6",
    "host_os": "Home Assistant OS 11.2",
    "docker_version": "24.0.7",
    "chassis": "embedded",
    "run_as_root": true
  },
  "custom_components": {
    "tedee": {
      "version": "2023.11.0",
      "requirements": [
        "pytedee-async==0.2.4"
      ]
    },
  "integration_manifest": {
    "domain": "tedee",
    "name": "Tedee",
    "codeowners": [
      "@patrickhilker",
      "@joerg65",
      "@zweckj"
    ],
    "config_flow": true,
    "dependencies": [
      "http"
    ],
    "documentation": "https://github.com/patrickhilker/tedee_hass_integration",
    "iot_class": "local_push",
    "issue_tracker": "https://github.com/patrickhilker/tedee_hass_integration/issues",
    "requirements": [
      "pytedee-async==0.2.4"
    ],
    "version": "2023.11.0",
    "is_built_in": false
  },
  "data": {
    "0": {
      "lock_name": "**REDACTED**",
      "lock_id": "**REDACTED**",
      "lock_type": 2,
      "state": 3,
      "battery_level": 99,
      "is_connected": true,
      "is_charging": false,
      "state_change_result": 1,
      "is_enabled_pullspring": true,
      "duration_pullspring": 3
    }
  }
}
```

**Comment by zweckj** [comment]
Can't reproduce that on my end. Got nothing to do with the semi locked though `"state_change_result": 1,` is what is causing that behaviour. So at some point your lock IS reporting that it's stuck.

**Comment by niwi-hh** [comment]
I tested this today again in a live-situation and you are right. For no obvious reason my lock was reporting to jammed after opening electronically but was still working without problem and without any obvious message in the app. I recalibrated my lock and now everything seems to be working as it should. Thank you for checking. I am sorry for not testing carefully enough before reporting.

**Comment by zweckj** [comment]
No need to apologize, glad you figured it out 👍
