### ISSUE TITLE
State does not change the icon

### ISSUE THREAD

**Issue by darkkatarsis** [patrickhilker/tedee_hass_integration#51]
I noticed that the entity that is from integration does not update the icon when changing the status. It seems to me that this is due to the fact that the device does not have the right device_class or the supported_features are different.

I am using beta version 2023.11.0b5

![ezgif-5-ee840f364d](https://github.com/patrickhilker/tedee_hass_integration/assets/24244919/960d1aee-053a-445f-9156-cda7131fdde9)
<img width="1159" alt="Screenshot 2023-12-15 at 14 52 29" src="https://github.com/patrickhilker/tedee_hass_integration/assets/24244919/121f3d30-c024-47cd-b212-e55284e3c473">

**Comment by zweckj** [comment]
Probably just because the icon is set statically. Will change it in the next update, but it should be fine in tile or mushroom cards anyways.

**Comment by zweckj** [comment]
shouldn't happen on the non-beta versions, the beta branch will not be taken further, as that part will move to HA core.
