### ISSUE TITLE
Use of homekit with this integration

### ISSUE THREAD

**Issue by Kaktus317** [patrickhilker/tedee_hass_integration#53]
Hi,
I have a problem, which apparently has to do with the use of this integration and I did not realize this at first:
I am using an older Teede Pro, which came without a homekit code. I tried out this integration a while ago, all good.
Then I saw that Homeassistant showed me a Homekit pairing code for the lock under "notifications" and I setup the lock with the homekit device integration - worked without a problem. I never really integrated the lock in automations. Now I was going to change that and thought, why use the cloud? Homekit offers everything I need (I think). Hence, I disabled this integration and did a lot of other stuff that day, so I did not figure this out till today:

When deleting this integration (and/or the API key?), the homekit device does not work anymore. When I install the integration, I see another notification for the homekit device with a **different** homekit code. Using that, I can install the homekit device again and the lock works. I think that is a bit strange, because homekit is suppose to be local and the homekit key is not suppose to change?
I don't understand how the integration is incluencing the lock's homekit feature. Or does the integration simulate a homekit device, which homeassistant then finds and the homekit integration does not communicate with the lock directly?

Since you have to detach the lock from the door, do a factory reset and add the lock to the app again for every "homkit add", this is really cumbersome and anyoing to figure out. Does anybody have an idea how I could use the homekit feature without depending on Tedee(s cloud)? It's a shame that Tedee does not stick to their advertised local API, since that needs an internet connection to the cloud every other day.

**Comment by zweckj** [comment]
If you have a HomeKit bridge enabled in HA, which includes locks then yes, HA will expose the HA device as HomeKit Device. You could even have both (tedee & HA lock) in Apple Home in parallel.

**Comment by Kaktus317** [comment]
Thanks for verifying that!
