### ISSUE TITLE
SUPPORT_OPEN was used from tedee, this is a deprecated constant which will be removed in HA Core 2025.1

### ISSUE THREAD

**Issue by coserotondo** [patrickhilker/tedee_hass_integration#54]
SUPPORT_OPEN was used from tedee, this is a deprecated constant which will be removed in HA Core 2025.1. Use LockEntityFeature.OPEN instead, please create a bug report at https://github.com/patrickhilker/tedee_hass_integration/issues

**Comment by zweckj** [comment]
fixed in 2024.1.0b1
