### ISSUE TITLE
Can't use this custom integration and the official one at the same time

### ISSUE THREAD

**Issue by LordShadowen** [patrickhilker/tedee_hass_integration#58]
I've been eagerly awaiting for the release of the official HA integration to test out the local API feature, which I really want to switch to. But before making the final move, I was also interested in comparing the two options, in terms of performance, how special cases were handled (e..g. partially locked), etc... 

I've upgrade today to 2024.2 and realized I can't have both - if the custom component is installed, it's the only one that shows up on the integration list. I have to remove it in order to get the official integration. 

I also tried removing it, configure the official one and then install the custom one on top to see what happens, but it breaks the configuration of the local bridges. 

Is this supposed to happen? Is there a workaround?

Also, on a separate note, while I got the official one working, I did some quick testing, and it is WAY slower at updating the state of a lock in HA when I manually lock/unlock it. Is this expected? By slow, I mean something like half a minute. This custom integration wasn't instant either, but I don't think it ever took more than maybe 5 to 10 seconds...

I thought one of the big advantages of the local API would be the use of callbacks so that we would get near-instant updates, no? Are my expectation incorrect?

**Comment by zweckj** [comment]
> Is this supposed to happen? Is there a workaround?

Yes it's intended like that, so normal users/don't mix match and encounter weird errors. If you install it manually (that is copying the folder in by yourself) you can change the `domain` in `manifest.json` and `const.py` which would allowing you running it in parallel.

> I thought one of the big advantages of the local API would be the use of callbacks so that we would get near-instant updates, no? Are my expectation incorrect?

No that's correct.But I had to pull that feature in 2024.2.0b3, as there was a bug which could crash your bridge. So no callbacks happening atm. Hoping to get it back latest 2024.3.0.

**Comment by LordShadowen** [comment]
> Yes it's intended like that, so normal users don't mix match and encounter weird errors. If you install it manually (that is copying the folder in by yourself) you can change the `domain` in `manifest.json` and `const.py` which would allow you to run it in parallel.
 
Ok, great to know - I'll try that.

> No that's correct.But I had to pull that feature in 2024.2.0b3, as there was a bug which could crash your bridge. So no callbacks happening atm. Hoping to get it back latest 2024.3.0.

Oh, I see. There's still hope then! :) 
Is there a ticket that I can follow about this?

Thanks
