### ISSUE TITLE
Incorrect "battery_charging" value

### ISSUE THREAD

**Issue by LordShadowen** [patrickhilker/tedee_hass_integration#6]
The attribute `battery_charging` is always `false`, even when the charger is plugged in.

**Comment by zweckj** [comment]
Can't reproduce, is this still active?

**Comment by LordShadowen** [comment]
I was going to check it with the latest version as mentioned in #10 , but as mentioned there, it doesn't work for me.
If we can get that going, I can test this again.

**Comment by LordShadowen** [comment]
Today I tested the latest 2023.7.0 and yes, this has been fixed

**Comment by zweckj** [comment]
@patrickhilker you can close that one
