### ISSUE TITLE
Unlock should unlock without pull spring even when automatic pull spring is enabled

### ISSUE THREAD

**Issue by rsporsche** [patrickhilker/tedee_hass_integration#8]
There is a parameter that can explicitly unlock without pulling the latch. Since there is an explicit option to 'open' the lock I think it would be best if 'unlock' did not pull the spring.

Could also be configurable if people have a user for that.

Refer:
https://tedee-tedee-api-doc.readthedocs-hosted.com/en/latest/endpoints/lock/unlock.html

Specifically, mode=2 for "unlock mode".

**Comment by zweckj** [comment]
Not possible at the moment. Unlock does either pull the latch or not, depending on what you set in the app for your lock.

**Comment by mluecke09** [comment]
It is possible to unlock without pull spring using the „mode“ parameter.
https://api.tedee.com/api/v1.30/my/lock/{id}/operation/unlock?mode={mode}

„mode=3“ should be used for unlock command an „mode=4“ for open command.

https://tedee-tedee-api-doc.readthedocs-hosted.com/en/latest/enums/unlock-mode.html explains the available mode parameters.

**Comment by patrickhilker** [comment]
Should be resolved with 2023.7.0
